import { aifriend1, ashadhiekadshi1, ashadhiekadshi2, assembly1, assembly2, assembly3, assembly4, assembly5, awards1, awards2, awards3, awards4, basketballtour1, basketballtour2, basketballtour3, classicaldance1, classicaldance2, diwalicelebration1, diwalicelebration2, diwalicelebration3, diwalicelebration4, evsday1, evsday2, ganeshamake1, ganeshamake10, ganeshamake2, ganeshamake3, ganeshamake4, ganeshamake5, ganeshamake6, ganeshamake7, ganeshamake8, ganpati1, ganpati2, gurupornima1, gurupornima2, gurupornima3, gurupornima4, independancday1, independancday2, InvestitureCere1, InvestitureCere2, InvestitureCere3, InvestitureCere4, InvestitureCere5, kargilday1, kargilday2, krishnajanmashtami1, krishnajanmashtami2, lecture1, lecture2, lecture3, lecture4, nagpanchami1, navratrid1, navratrid2, navratrid3, ourfaculty, parentsmeet1, parentsmeet2, rakhi1, rakhi2, rakhi3, rakhi4, rakhi5, rakhi6, rakhi7, ramdandee1, ramdandee2, ramdandee3, ranilaxmibaiskit1, ranilaxmibaiskit2, sant_tulshidas1, sant_tulshidas2, schoolinfra2, schoolinfra3, sportsday1, sportsday2, sportsday3, sportsdayaward1, sportsdayaward2, sportsdayaward3, staffmeet1, staffmeet2, staffmeet3, staffmeet4, teacherorientation1, teacherorientation2, teacherstraining1, teacherstraining2, teaching1, teaching2, tilakpunyathithi1, varsharambhupasana1, varsharambhupasana2, yogaday1, yogaday2, yogaday3 } from "../../assets";

// constant/GalleryData/primarySecondaryGalleryData.js
const primarySecondaryGalleryData = {
  id: "primary-secondary",
  title: "Primary & Secondary Section",
  icon: "",
  subcategories: [
    {
      id: "activity",
      title: "Activity",
      icon: "",
      items: [
        {
          id: 1,
          title: "Award Ceremony",
          image: awards1,
          //date: "2024-09-20",
          description: "Annual art exhibition showcasing student creativity",
          alt: "Award Ceremony",
        },
        {
          id: 2,
          title: "Award Ceremony",
          image: awards2,
        //   date: "2024-03-15",
          description: "Annual award distribution ceremony for academic excellence",
          alt: "Award ceremony",
        },
        {
          id: 3,
          title: "Award Ceremony",
          image: awards3,
          //date: "2024-08-10",
          description: "Raksha Bandhan special rakhi making workshop",
          alt: "Award Ceremony",
        },
        {
          id: 4,
          title: "Award Ceremony",
          image: awards4,
          date: "2024-09-05",
          description: "Clay Ganesha making activity for Ganesh Chaturthi",
          alt: "Award Ceremony",
        },
        {
          id: 5,
          title: "Rakhi Making Activity",
          image: rakhi1,
          date: "2024-09-05",
          description: "Clay Ganesha making activity for Ganesh Chaturthi",
          alt: "Rakhi Making Activity",
        },
        {
          id: 6,
          title: "Rakhi Making Activity ",
          image: rakhi2,
          date: "2024-09-05",
          description: "Clay Ganesha making activity for Ganesh Chaturthi",
          alt: "Rakhi Making Activity ",
        },
        {
          id: 7,
          title: "Rakhi Making  Activity",
          image: rakhi3,
          date: "2024-09-05",
          description: "Clay Ganesha making activity for Ganesh Chaturthi",
          alt: "Rakhi Making Activity ",
        },
        {
          id: 8,
          title: "Rakhi Making Activity ",
          image: rakhi4,
          date: "2024-09-05",
          description: "Clay Ganesha making activity for Ganesh Chaturthi",
          alt: "Rakhi Making Activity ",
        },
        {
          id: 9,
          title: "Rakhi Making Activity",
          image: rakhi5,
          date: "2024-09-05",
          description: "Clay Ganesha making activity for Ganesh Chaturthi",
          alt: "Rakhi Making Activity",
        },
        {
          id: 10,
          title: "Ganesha Making Activity ",
          image: ganeshamake1,
          //date: "2024-09-05",
          description: "Clay Ganesha making activity for Ganesh Chaturthi",
          alt: "Rakhi Making Activity",
        },
        {
          id: 11,
          title: "Ganesha Making Activity",
          image: ganeshamake2,
          date: "2024-09-05",
          description: "Clay Ganesha making activity for Ganesh Chaturthi",
          alt: "Rakhi Making Activity",
        },
        {
          id: 12,
          title: "Ganesha Making Activity",
          image: ganeshamake3,
          date: "2024-09-05",
          description: "Clay Ganesha making activity for Ganesh Chaturthi",
          alt: "Rakhi Making Activity",
        },
        {
          id: 13,
          title: "Ganesha Making Activity",
          image: ganeshamake4,
          date: "2024-09-05",
          description: "Clay Ganesha making activity for Ganesh Chaturthi",
          alt: "Rakhi Making Activity",
        },
        {
          id: 14,
          title: "Ganesha Making Activity",
          image: ganeshamake4,
          date: "2024-09-05",
          description: "Clay Ganesha making activity for Ganesh Chaturthi",
          alt: "Rakhi Making Activity",
        },
        {
          id: 15,
          title: "Ganesha Making Activity",
          image: ganeshamake5,
          date: "2024-09-05",
          description: "Clay Ganesha making activity for Ganesh Chaturthi",
          alt: "Rakhi Making Activity",
        },
        {
          id: 16,
          title: "Ganesha Making Activity",
          image: ganeshamake6,
          date: "2024-09-05",
          description: "Clay Ganesha making activity for Ganesh Chaturthi",
          alt: "Rakhi Making Activity",
        },
        {
          id: 17,
          title: "Ganesha Making Activity",
          image: ganeshamake7,
          date: "2024-09-05",
          description: "Clay Ganesha making activity for Ganesh Chaturthi",
          alt: "Rakhi Making Activity",
        },
        {
          id: 18,
          title: "Ganesha Making Activity",
          image: ganeshamake8,
          date: "2024-09-05",
          description: "Clay Ganesha making activity for Ganesh Chaturthi",
          alt: "Rakhi Making Activity",
        },
        // {
        //   id: 19,
        //   title: "Rakhi Making Activity",
        //   image: rakhi7,
        //   date: "2024-09-05",
        //   description: "Clay Ganesha making activity for Ganesh Chaturthi",
        //   alt: "Rakhi Making Activity",
        // },
        // {
        //   id: 20,
        //   title: "Rakhi Making Activity",
        //   image: rakhi7,
        //   date: "2024-09-05",
        //   description: "Clay Ganesha making activity for Ganesh Chaturthi",
        //   alt: "Rakhi Making Activity",
        // },
      ],
    },
    {
      id: "assembly",
      title: "Assembly",
      icon: "🎤",
      items: [
        {
          id: 1,
          title: "Morning Assembly",
          image: assembly1,
        //   date: "2024-10-10",
          description: "Daily morning assembly with prayers and announcements",
          alt: "School morning assembly",
        },
         {
          id: 2,
          title: "Morning Assembly",
          image: assembly2,
        //   date: "2024-10-10",
          description: "Daily morning assembly with prayers and announcements",
          alt: "School morning assembly",
        },
         {
          id: 3,
          title: "Morning Assembly",
          image: assembly3,
        //   date: "2024-10-10",
          description: "Daily morning assembly with prayers and announcements",
          alt: "School morning assembly",
        },
         {
          id: 4,
          title: "Morning Assembly",
          image: assembly4,
        //   date: "2024-10-10",
          description: "Daily morning assembly with prayers and announcements",
          alt: "School morning assembly",
        },
         {
          id: 5,
          title: "Morning Assembly",
          image: assembly5,
        //   date: "2024-10-10",
          description: "Daily morning assembly with prayers and announcements",
          alt: "School morning assembly",
        },
        
      ],
    },
    {
      id: "class-teaching",
      title: "Class Teaching",
      icon: "",
      items: [
        {
          id: 1,
          title: "Class Teaching",
          image: teaching1,
          //date: "2024-11-05",
          description: "Interactive science teaching session",
          alt: "Science class teaching",
        },
        {
          id: 2,
          title: "Class Teaching",
          image: teaching2,
          //date: "2024-11-05",
          description: "Interactive science teaching session",
          alt: "Science class teaching",
        },
      ],
    },
    {
      id: "co-curricular",
      title: "Co-curricular Activity",
      icon: "",
      items: [
        {
          id: 1,
          title: "Investiture Ceremony",
          image: InvestitureCere1,
          date: "2024-07-01",
          description: "Annual investiture ceremony for student council",
          alt: "Investiture ceremony",
        },
        {
          id: 2,
          title: "Investiture Ceremony",
          image: InvestitureCere2,
          date: "2024-07-01",
          description: "Annual investiture ceremony for student council",
          alt: "Investiture ceremony",
        },
        {
          id: 3,
          title: "Investiture Ceremony",
          image: InvestitureCere3,
          date: "2024-07-01",
          description: "Annual investiture ceremony for student council",
          alt: "Investiture ceremony",
        },
        {
          id: 4,
          title: "Investiture Ceremony",
          image: InvestitureCere4,
          date: "2024-07-01",
          description: "Annual investiture ceremony for student council",
          alt: "Investiture ceremony",
        },
        {
          id: 5,
          title: "Investiture Ceremony",
          image: InvestitureCere5,
          date: "2024-07-01",
          description: "Annual investiture ceremony for student council",
          alt: "Investiture ceremony",
        },
      ],
    },
    {
      id: "Primary and Secondary - cultural",
      title: "Cultural",
      icon: "",
      items: [
        {
          id: 1,
          title: "Ashadi Ekadashi",
          image: ashadhiekadshi1,
          date: "2024-07-17",
          description: "Ashadi Ekadashi procession and celebration",
          alt: "Ashadi Ekadashi cultural event",
        },
        {
          id: 2,
          title: "Ashadi Ekadashi",
          image: ashadhiekadshi2,
          date: "2024-07-17",
          description: "Ashadi Ekadashi procession and celebration",
          alt: "Ashadi Ekadashi cultural event",
        },
        {
          id: 3, 
          title: "Ganpati Festival",
          image: ganpati1,
          date: "2024-09-10",
          description: "Ganesh Chaturthi celebration in school",
          alt: "Ganpati festival",
        },
        {
          id: 4, 
          title: "Ganpati Festival",
          image: ganpati2,
          date: "2024-09-10",
          description: "Ganesh Chaturthi celebration in school",
          alt: "Ganpati festival",
        },
        {
          id: 5,
          title: "Guru Purnima",
          image: gurupornima1,
          date: "2024-07-21",
          description: "Guru Purnima celebration honoring teachers",
          alt: "Guru Purnima celebration",
        },
        {
          id: 6,
          title: "Guru Purnima",
          image: gurupornima2,
          date: "2024-07-21",
          description: "Guru Purnima celebration honoring teachers",
          alt: "Guru Purnima celebration",
        },
        {
          id: 7,
          title: "Guru Purnima",
          image: gurupornima3,
          date: "2024-07-21",
          description: "Guru Purnima celebration honoring teachers",
          alt: "Guru Purnima celebration",
        },
        {
          id: 8,
          title: "Guru Purnima",
          image: gurupornima4,
          date: "2024-07-21",
          description: "Guru Purnima celebration honoring teachers",
          alt: "Guru Purnima celebration",
        },
        {
          id: 4,
          title: "Independence Day",
          image: independancday1,
          date: "2024-08-15",
          description: "Independence Day flag hoisting and cultural program",
          alt: "Independence Day celebration",
        },
        {
          id: 4,
          title: "Independence Day",
          image: independancday2,
          date: "2024-08-15",
          description: "Independence Day flag hoisting and cultural program",
          alt: "Independence Day celebration",
        },
        {
          id: 5,
          title: "Krishna Janmashtami",
          image: krishnajanmashtami1,
          date: "2024-08-30",
          description: "Janmashtami celebration with dahi handi and cultural programs",
          alt: "Krishna Janmashtami celebration",
        },
        {
          id: 6,
          title: "Krishna Janmashtami",
          image: krishnajanmashtami2,
          date: "2024-08-30",
          description: "Janmashtami celebration with dahi handi and cultural programs",
          alt: "Krishna Janmashtami celebration",
        },
        {
          id: 6,
          title: "Navaratri Dance",
          image: navratrid1,
          date: "2024-10-05",
          description: "Navaratri Garba and Dandiya celebrations",
          alt: "Navaratri dance performance",
        },
        {
          id: 6,
          title: "Navaratri Dance",
          image: navratrid2,
          date: "2024-10-05",
          description: "Navaratri Garba and Dandiya celebrations",
          alt: "Navaratri dance performance",
        },
        {
          id: 6,
          title: "Navaratri Dance",
          image: navratrid3,
          date: "2024-10-05",
          description: "Navaratri Garba and Dandiya celebrations",
          alt: "Navaratri dance performance",
        },
        {
          id: 7,
          title: "Yoga Day",
          image: yogaday1,
          date: "2024-06-21",
          description: "International Yoga Day celebration",
          alt: "Yoga day activities",
        },
        {
          id: 7,
          title: "Yoga Day",
          image: yogaday2,
          date: "2024-06-21",
          description: "International Yoga Day celebration",
          alt: "Yoga day activities",
        },
        {
          id: 7,
          title: "Yoga Day",
          image: yogaday3,
          date: "2024-06-21",
          description: "International Yoga Day celebration",
          alt: "Yoga day activities",
        },
      ],
    },
    {
      id: "extra-curricular",
      title: "Extra Curricular Activity",
      icon: "",
      items: [
        {
          id: 1,
          title: "Elocution Competition",
          image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
          date: "2024-11-20",
          description: "Inter-house elocution competition",
          alt: "Elocution competition",
        },
      ],
    },
    {
      id: "felicitate",
      title: "Felicitate",
      icon: "",
      items: [
        {
          id: 1,
          title: "Sports Day Awards",
          image: sportsdayaward1,
          date: "2024-02-15",
          description: "Annual sports day award distribution",
          alt: "Sports day awards",
        },
        {
          id: 2,
          title: "Sports Day Awards",
          image: sportsdayaward2,
          date: "2024-02-15",
          description: "Annual sports day award distribution",
          alt: "Sports day awards",
        },
        {
          id: 3,
          title: "Sports Day Awards",
          image: sportsdayaward3,
          date: "2024-02-15",
          description: "Annual sports day award distribution",
          alt: "Sports day awards",
        },
      ],
    },
    {
      id: "lectures",
      title: "Lectures",
      icon: "",
      items: [
        {
          id: 1,
          title: "Academic Lecture Series",
          image: lecture1,
          date: "2024-09-25",
          description: "Special academic lectures by guest speakers",
          alt: "Academic lecture",
        },
        {
          id: 2,
          title: "Academic Lecture Series",
          image: lecture2,
          date: "2024-09-25",
          description: "Special academic lectures by guest speakers",
          alt: "Academic lecture",
        },
        {
          id: 3,
          title: "Special Lecture",
          image: lecture3,
          date: "2024-10-10",
          description: "Special motivational lecture for students",
          alt: "Special lecture",
        },
        {
          id: 4,
          title: "Special Lecture",
          image: lecture4,
          date: "2024-10-10",
          description: "Special motivational lecture for students",
          alt: "Special lecture",
        },
        {
          id: 4,
          title: "Varsharambh Upasana",
          image: varsharambhupasana1,
          date: "2024-06-15",
          description: "Academic year beginning prayer ceremony",
          alt: "Varsharambh Upasana",
        },
        {
          id: 5,
          title: "Varsharambh Upasana",
          image: varsharambhupasana2,
          date: "2024-06-15",
          description: "Academic year beginning prayer ceremony",
          alt: "Varsharambh Upasana",
        },
      ],
    },
    {
      id: "meetings",
      title: "Meetings",
      icon: "",
      items: [
        {
          id: 1,
          title: "Parents Meeting",
          image: parentsmeet1,
          date: "2024-11-10",
          description: "PTA meeting with parents and teachers",
          alt: "Parents meeting",
        },
        {
          id: 2,
          title: "Parents Meeting",
          image: parentsmeet2,
          date: "2024-10-05",
          description: "Monthly staff meeting and planning session",
          alt: "Staff meeting",
        },
        {
          id: 3,
          title: "Staff Meeting",
          image: staffmeet1,
          date: "2024-10-05",
          description: "Monthly staff meeting and planning session",
          alt: "Staff meeting",
        },
        {
          id: 4,
          title: "Staff Meeting",
          image: staffmeet2,
          date: "2024-10-05",
          description: "Monthly staff meeting and planning session",
          alt: "Staff meeting",
        },
        {
          id: 4,
          title: "Staff Meeting",
          image: staffmeet3,
          date: "2024-10-05",
          description: "Monthly staff meeting and planning session",
          alt: "Staff meeting",
        },
        {
          id: 4,
          title: "Staff Meeting",
          image: staffmeet4,
          date: "2024-10-05",
          description: "Monthly staff meeting and planning session",
          alt: "Staff meeting",
        },
      ],
    },
    {
      id: "ramdandee",
      title: "Ramdandee",
      icon: "",
      items: [
        {
          id: 1,
          title: "NDA Activity",
          image: ramdandee1,
          date: "2024-08-20",
          description: "National Discipline Army (NDA) activities and drills",
          alt: "NDA ramdandee activity",
        },
        {
          id: 2,
          title: "NDA Activity",
          image: ramdandee2,
          date: "2024-08-20",
          description: "National Discipline Army (NDA) activities and drills",
          alt: "NDA ramdandee activity",
        },
        {
          id: 3,
          title: "NDA Activity",
          image: ramdandee3,
          date: "2024-08-20",
          description: "National Discipline Army (NDA) activities and drills",
          alt: "NDA ramdandee activity",
        },
      ],
    },
    {
      id: "school-infrastructure",
      title: "School Infrastructure",
      icon: "",
      items: [
        {
          id: 1,
          title: "School Building",
          image: schoolinfra2,
          date: "2024-01-15",
          description: "Modern school infrastructure and facilities",
          alt: "School infrastructure",
        },
        {
          id: 2,
          title: "School Building",
          image: schoolinfra3,
          date: "2024-01-15",
          description: "Modern school infrastructure and facilities",
          alt: "School infrastructure",
        },
      ],
    },
    {
      id: "sports",
      title: "Sports",
      icon: "",
      items: [
        {
          id: 1,
          title: "Basketball Tournament",
          image: basketballtour1,
          date: "2024-03-10",
          description: "Inter-school basketball tournament",
          alt: "Basketball tournament",
        },
        {
          id: 2,
          title: "Basketball Tournament",
          image: basketballtour2,
          date: "2024-03-10",
          description: "Inter-school basketball tournament",
          alt: "Basketball tournament",
        },
        {
          id: 3,
          title: "Basketball Tournament",
          image: basketballtour3,
          date: "2024-03-10",
          description: "Inter-school basketball tournament",
          alt: "Basketball tournament",
        },
        {
          id: 4,
          title: "National Sports Day",
          image: sportsday1,
          date: "2024-08-29",
          description: "National Sports Day celebrations and competitions",
          alt: "National Sports Day",
        },
        {
          id: 5,
          title: "National Sports Day",
          image: sportsday2,
          date: "2024-08-29",
          description: "National Sports Day celebrations and competitions",
          alt: "National Sports Day",
        },
        {
          id: 6,
          title: "National Sports Day",
          image: sportsday3,
          date: "2024-08-29",
          description: "National Sports Day celebrations and competitions",
          alt: "National Sports Day",
        },
      ],
    },
    {
      id: "staff",
      title: "Staff",
      icon: "",
      items: [
        {
          id: 1,
          title: "Staff Group Photo",
          image: ourfaculty,
          date: "2024-06-30",
          description: "Annual staff group photograph",
          alt: "Staff group photo",
        },
      ],
    },
    {
      id: "students-skite",
      title: "Students Skite",
      icon: "",
      items: [
        {
          id: 1,
          title: "World Environment Day",
          image: evsday1,
          date: "2024-06-05",
          description: "Environment day awareness skit",
          alt: "World Environment Day skit",
        },
        {
          id: 1,
          title: "World Environment Day",
          image: evsday2,
          date: "2024-06-05",
          description: "Environment day awareness skit",
          alt: "World Environment Day skit",
        },
        {
          id: 2,
          title: "Tilak Punyatithi",
          image: tilakpunyathithi1,
          date: "2024-08-01",
          description: "Skit on Lokmanya Tilak's life and teachings",
          alt: "Tilak Punyatithi skit",
        },
        {
          id: 3,
          title: "Sant Tulsidas Jayanti",
          image: sant_tulshidas1,
          date: "2024-08-11",
          description: "Skit celebrating Sant Tulsidas Jayanti",
          alt: "Sant Tulsidas Jayanti skit",
        },
        {
          id: 4,
          title: "Sant Tulsidas Jayanti",
          image: sant_tulshidas2,
          date: "2024-08-11",
          description: "Skit celebrating Sant Tulsidas Jayanti",
          alt: "Sant Tulsidas Jayanti skit",
        },
        {
          id: 4,
          title: "Rani Laxmi Bai Skit",
          image: ranilaxmibaiskit1,
          date: "2024-11-19",
          description: "Dramatic portrayal of Rani Laxmi Bai's life",
          alt: "Rani Laxmi Bai skit",
        },
        {
          id: 4,
          title: "Rani Laxmi Bai Skit",
          image: ranilaxmibaiskit2,
          date: "2024-11-19",
          description: "Dramatic portrayal of Rani Laxmi Bai's life",
          alt: "Rani Laxmi Bai skit",
        },
        {
          id: 5,
          title: "Navratri Skit",
          image: navratrid1,
          date: "2024-10-03",
          description: "Navratri themed cultural skit",
          alt: "Navratri skit",
        },
        {
          id: 5,
          title: "Navratri Skit",
          image: navratrid2,
          date: "2024-10-03",
          description: "Navratri themed cultural skit",
          alt: "Navratri skit",
        },
        {
          id: 5,
          title: "Navratri Skit",
          image: navratrid3,
          date: "2024-10-03",
          description: "Navratri themed cultural skit",
          alt: "Navratri skit",
        },
        {
          id: 6,
          title: "Nagpanchami Skit",
          image: nagpanchami1,
          date: "2024-08-08",
          description: "Nagpanchami celebration skit",
          alt: "Nagpanchami skit",
        },
        {
          id: 7,
          title: "Kargil Day Skit",
          image: kargilday1,
          date: "2024-07-26",
          description: "KG section Kargil Day remembrance skit",
          alt: "Kargil Day skit",
        },
        {
          id: 7,
          title: "Kargil Day Skit",
          image: kargilday2,
          date: "2024-07-26",
          description: "KG section Kargil Day remembrance skit",
          alt: "Kargil Day skit",
        },
        {
          id: 8,
          title: "Indian Classical Dance",
          image: classicaldance1,
          date: "2024-09-15",
          description: "Indian classical dance performance by students",
          alt: "Indian classical dance",
        },
        {
          id: 8,
          title: "Indian Classical Dance",
          image: classicaldance2,
          date: "2024-09-15",
          description: "Indian classical dance performance by students",
          alt: "Indian classical dance",
        },
        {
          id: 9,
          title: "Diwali Skit",
          image: diwalicelebration1,
          date: "2024-11-12",
          description: "Diwali festival themed skit",
          alt: "Diwali skit",
        },
        {
          id: 9,
          title: "Diwali Skit",
          image: diwalicelebration2,
          date: "2024-11-12",
          description: "Diwali festival themed skit",
          alt: "Diwali skit",
        },
        {
          id: 9,
          title: "Diwali Skit",
          image: diwalicelebration3,
          date: "2024-11-12",
          description: "Diwali festival themed skit",
          alt: "Diwali skit",
        },
        {
          id: 9,
          title: "Diwali Skit",
          image: diwalicelebration4,
          date: "2024-11-12",
          description: "Diwali festival themed skit",
          alt: "Diwali skit",
        },
        {
          id: 10,
          title: "AI Friend and Foe Script",
          image: aifriend1,
          date: "2024-10-25",
          description: "Skit on artificial intelligence - friend and foe",
          alt: "AI friend and foe skit",
        },
      ],
    },
    {
      id: "teachers",
      title: "Teachers",
      icon: "",
      items: [
        {
          id: 1,
          title: "Teacher Orientation",
          image: teacherorientation1,
          date: "2024-06-01",
          description: "Teacher orientation program for new academic year",
          alt: "Teacher orientation",
        },
        {
          id: 2,
          title: "Teacher Orientation",
          image: teacherorientation2,
          date: "2024-06-01",
          description: "Teacher orientation program for new academic year",
          alt: "Teacher orientation",
        },
        {
          id: 3,
          title: "Teacher Training",
          image: teacherstraining1,
          date: "2024-07-15",
          description: "Professional development training for teachers",
          alt: "Teacher training session",
        },
        {
          id: 4,
          title: "Teacher Training",
          image: teacherstraining2,
          date: "2024-07-15",
          description: "Professional development training for teachers",
          alt: "Teacher training session",
        },
      ],
    },
  ],
};

export default primarySecondaryGalleryData;